apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitor-ns
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets: []

    rule_files: []

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
            labels:
              app: "prometheus"

      - job_name: "service"
        kubernetes_sd_configs:
          - role: endpoints

        relabel_configs:
          # 只保留 Service 注解 prometheus.io/scrape=true 的
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true

          # 设置抓取协议 http/https
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
            action: replace
            target_label: __scheme__
            regex: (https?)

          # 设置 metrics 路径
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)

          # 替换端口
          - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2

          # 映射 Service label
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)

          # namespace 映射
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace

          # service 名称映射
          - source_labels: [__meta_kubernetes_service_name]
            action: replace
            target_label: kubernetes_name

          # pod 名称映射
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name