apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-cfg
  namespace: traefik
data:
  traefik.yaml: |-
    api:
      insecure: true
      dashboard: true
    ping: {}
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
    providers:
      kubernetesCRD: {}
      kubernetesIngress: {}
    log:
      level: ERROR